name: C++ CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cppcheck cmake libgtest-dev

    - name: Static analysis with cppcheck
      run: cppcheck --enable=all --inconclusive --std=c++17 src

    - name: Build with make
      run: make

    - name: Run tests (Google Test)
      run: make test